Update second batch of examples to manifest SDK 3.0 ACAPs

diff --git a/vdo-larod-preprocessing/Dockerfile b/vdo-larod-preprocessing/Dockerfile
--- a/vdo-larod-preprocessing/Dockerfile
+++ b/vdo-larod-preprocessing/Dockerfile
@@ -21,5 +21,15 @@ RUN curl -o mobilenet_v2_1.0_224_quant.tgz http://download.tensorflow.org/models
 WORKDIR /opt/app
 COPY ./app .
 
+ARG CHIP=CPU
 # Building the ACAP application
-RUN . /opt/axis/acapsdk/environment-setup* && create-package.sh
+RUN if [ "$CHIP" = CPU ]; then \
+	. /opt/axis/acapsdk/environment-setup* && acap-build . \
+	-a 'model/mobilenet_v2_1.0_224_quant.larod'; \
+	elif [ "$CHIP" = EDGETPU ]; then \
+	. /opt/axis/acapsdk/environment-setup* && acap-build . \
+	-a 'model/mobilenet_v2_1.0_224_quant_edgetpu.larod'; \
+	else \
+	echo 'Error:' $CHIP 'is not a valid value for the CHIP variable'; \
+	exit 1; \
+	fi
diff --git a/vdo-larod/Dockerfile b/vdo-larod/Dockerfile
--- a/vdo-larod/Dockerfile
+++ b/vdo-larod/Dockerfile
@@ -31,5 +31,15 @@ RUN mkdir -p lib include && \
   ln -s libyuv.so.1 libyuv.so && \
   ln -s libyuv.so.1 libyuv.so.1.0
 
+ARG CHIP=CPU
 # Building the ACAP application
-RUN . /opt/axis/acapsdk/environment-setup* && create-package.sh
+RUN if [ "$CHIP" = CPU ]; then \
+  . /opt/axis/acapsdk/environment-setup* && acap-build . \
+  -a 'label/imagenet_labels.txt' -a 'model/mobilenet_v2_1.0_224_quant.larod'; \
+  elif [ "$CHIP" = EDGETPU ]; then \
+  . /opt/axis/acapsdk/environment-setup* && acap-build . \
+  -a 'label/imagenet_labels.txt' -a 'model/mobilenet_v2_1.0_224_quant_edgetpu.larod'; \
+  else \
+  echo 'Error:' $CHIP 'is not a valid value for the CHIP variable'; \
+  exit 1; \
+  fi
diff --git a/vdo-larod2/Dockerfile b/vdo-larod2/Dockerfile
--- a/vdo-larod2/Dockerfile
+++ b/vdo-larod2/Dockerfile
@@ -15,5 +15,15 @@ FROM ${REPO}/${SDK}:${VERSION}-${ARCH}-ubuntu${UBUNTU_VERSION}
 WORKDIR /opt/app
 COPY ./app /opt/app/
 
+ARG CHIP=CPU
 # Building the ACAP application
-RUN . /opt/axis/acapsdk/environment-setup* && create-package.sh
+RUN if [ "$CHIP" = CPU ]; then \
+    . /opt/axis/acapsdk/environment-setup* && acap-build . \
+    -a 'label/imagenet_labels.txt' -a 'model/mobilenet_v2_1.0_224_quant.larod'; \
+    elif [ "$CHIP" = EDGETPU ]; then \
+    . /opt/axis/acapsdk/environment-setup* && acap-build . \
+    -a 'label/imagenet_labels.txt' -a 'model/mobilenet_v2_1.0_224_quant_edgetpu.larod'; \
+    else \
+    echo 'Error:' $CHIP 'is not a valid value for the CHIP variable'; \
+    exit 1; \
+    fi
