Add utility script for test and convenience

diff --git a/.github/workflows/reproducible-package.yml b/.github/workflows/reproducible-package.yml
--- a/.github/workflows/reproducible-package.yml
+++ b/.github/workflows/reproducible-package.yml
@@ -10,40 +10,36 @@ jobs:
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v2
-      #- uses: actions/checkout@master
-      # this will enable shellCheck to be performed
-      # on every push to the repo.
-    #- name: Run ShellCheck
-      #uses: ludeeus/action-shellcheck@master
-      # If shellCheck complains about unnecessery things, ignore it.
-      #env:
-        #SHELLCHECK_OPTS: -e SC2153 -e SC2148
 
-    # Build reproducible-package application
-    - name: Build reproducible-package application
+    - name: Build and test reproducible package application
       run: |
+        found_error=n
+
         cd reproducible-package
-        docker build --no-cache --tag rep1 .
-        docker cp $(docker create rep:1):/opt/app ./build1
-
-        docker build --no-cache --build-arg TIMESTAMP="$(git log -1 --pretty=%ct)" --tag rep2 .
-        docker cp $(docker create rep2):/opt/app ./build2
-
-        docker build --no-cache --build-arg TIMESTAMP="$(git log -1 --pretty=%ct)" --tag rep3 .
-        docker cp $(docker create rep3):/opt/app ./build3
+        # Make use of utility script and test it at the same time!
+        ./reproducible_package.sh build
 
         # Check that standard and reproducible packages diff
+        printf "Compare standard package to reproducible package\n"
         if cmp build1/*.eap build2/*.eap; then
-          printf "Error: The standard and reproducible packages are identical which was not expected"
-          exit 1
+          printf "Error: Packages are identical which was not expected\n"
+          found_error=y
         else
-          printf "The packages diff as expected\n"
+          printf "OK: The packages diff as expected\n"
         fi
 
         # Check that the two reproducible packages are identical
+        printf "Compare two reproducible packages\n"
         if cmp build2/*.eap build3/*.eap; then
-          printf "The packages are identical as expected\n"
+          printf "OK: The packages are identical as expected\n"
         else
-          printf "Error: The reproducbile packages diff which was not expected"
-          exit 1
+          printf "Error: The reproducible packages diff which was not expected\n"
+          found_error=y
         fi
+
+        # Cleanup
+        # Make use of utility script and test it at the same time!
+        printf "Run cleanup of build directories and images\n"
+        ./reproducible_package.sh clean
+
+        [ "$found_error" = n ] || exit 1
